### ISSUE TITLE
Picture1

### ISSUE THREAD

**Issue by Tom-Bombadil** [Conte-Ecology/shedsData#2]
![picture1](https://cloud.githubusercontent.com/assets/6216239/13363884/d7e9165c-dc99-11e5-9adb-bf80aec91476.png)

**Comment by djhocking** [comment]
Will you have med, high, and high-truncated (what we use)?

**Comment by Tom-Bombadil** [comment]
I wasn't planning on it. Right now I'm just trying to upload images to use in GitHub Pages site. They suggested uploading images via issues to reference.
